// Copyright 2023 Drunella
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ----------------------------------------------------------------------------


#include <stdbool.h>
#include <stdio.h>
#include <conio.h>
#include <string.h>
#include <ctype.h>
#include <stdlib.h>

#include "util.h"
#include "editor.h"


item_name_t item_names[256] = {
    { 0x00, NULL                ,  0 },
    { 0x01, "Torch"             ,  1 },
    { 0x02, "Lamp"              ,  1 },
    { 0x03, "Broadsword"        ,  0 },
    { 0x04, "Short Sword"       ,  0 },
    { 0x05, "Dagger"            ,  0 },
    { 0x06, "War Axe"           ,  1 },
    { 0x07, "Halbard"           ,  0 },
    { 0x08, "Long Bow"          ,  0 },
    { 0x09, "Staff"             ,  0 },
    { 0x0a, "Buckler"           ,  0 },
    { 0x0b, "Tower Shield"      ,  0 },
    { 0x0c, "Leather Armor"     ,  0 },
    { 0x0d, "Chain Mail"        ,  0 },
    { 0x0e, "Scale Armor"       ,  0 },
    { 0x0f, "Plate Armor"       ,  0 },
    { 0x10, "Robes"             ,  0 },
    { 0x11, "Helm"              ,  0 },
    { 0x12, "Leather Gloves"    ,  0 },
    { 0x13, "Gauntlets"         ,  0 },
    { 0x14, "Mandolin"          ,  0 },
    { 0x15, "Spear"             ,  1 },
    { 0x16, "Arrows"            , 24 },
    { 0x17, "Mthr Sword"        ,  0 },
    { 0x18, "Mthr Shield"       ,  0 },
    { 0x19, "Mthr Chain"        ,  0 },
    { 0x1a, "Mthr Scale"        ,  0 },
    { 0x1b, "Giant Fgn"         ,  1 },
    { 0x1c, "Mthr Bracers"      ,  0 },
    { 0x1d, "Bardsword"         ,  0 },
    { 0x1e, "Fire Horn"         , 50 },
    { 0x1f, "Litewand"          , 80 },
    { 0x20, "Mthr Dagger"       ,  0 },
    { 0x21, "Mthr Helm"         ,  0 },
    { 0x22, "Mthr Gloves"       ,  0 },
    { 0x23, "Mthr Axe"          ,  1 },
    { 0x24, "Shuriken"          ,  1 },
    { 0x25, "Mthr Plate"        ,  0 },
    { 0x26, "Molten Fgn"        ,  1 },
    { 0x27, "Spell Spear"       ,  1 },
    { 0x28, "Shield Ring"       ,  0 },
    { 0x29, "Fin's Flute"       ,  0 },
    { 0x2a, "Kael's Axe"        ,  1 },
    { 0x2b, "Mthr Arrows"       , 10 },
    { 0x2c, "Dayblade"          , 80 },
    { 0x2d, "Shield Staff"      ,  0 },
    { 0x2e, "Elf Cloak"         ,  0 },
    { 0x2f, "Hawkblade"         ,  0 },
    { 0x30, "Admt Sword"        ,  0 },
    { 0x31, "Admt Shield"       ,  0 },
    { 0x32, "Admt Helm"         ,  0 },
    { 0x33, "Admt Gloves"       ,  0 },
    { 0x34, "Pureblade"         ,  0 },
    { 0x35, "Boomerang"         ,  0 },
    { 0x36, "Ali's Carpet"      , 50 },
    { 0x37, "Luckshield"        ,  0 },
    { 0x38, "Dozer Fgn"         ,  1 },
    { 0x39, "Admt Chain"        ,  0 },
    { 0x3a, "Death Stars"       ,  4 },
    { 0x3b, "Admt Plate"        ,  0 },
    { 0x3c, "Admt Bracers"      ,  0 },
    { 0x3d, "Slayer Fgn"        ,  1 },
    { 0x3e, "Pure Shield"       ,  0 },
    { 0x3f, "Mage Staff"        ,  0 },
    { 0x40, "War Staff"         ,  0 },
    { 0x41, "Thief Dagger"      ,  0 },
    { 0x42, "Soul Mace"         ,  0 },
    { 0x43, "Ogrewand"          , 88 },
    { 0x44, "Kato's bracer"     ,  0 },
    { 0x45, "Sorcerstaff"       , 80 },
    { 0x46, "Galt's Flute"      , 88 },
    { 0x47, "Frost Horn"        , 65 },
    { 0x48, "Ag's Arrows"       , 10 },
    { 0x49, "Dmnd Shield"       ,  0 },
    { 0x4a, "Bard Bow"          ,  0 },
    { 0x4b, "Dmnd Helm"         ,  0 },
    { 0x4c, "Elf Boots"         ,  0 },
    { 0x4d, "Vanquisher Fgn"    ,  1 },
    { 0x4e, "Conjurstaff"       ,  0 },
    { 0x4f, "Staff of Lor"      , 35 },
    { 0x50, "Flame Sword"       ,  0 },
    { 0x51, "Powerstaff"        , 51 },
    { 0x52, "Breath Ring"       ,  0 },
    { 0x53, "Dragonshield"      , 20 },
    { 0x54, "Dmnd Plate"        ,  0 },
    { 0x55, "Wargloves"         ,  0 },
    { 0x56, "Wizhelm"           , 25 },
    { 0x57, "Dragonwand"        , 35 },
    { 0x58, "Deathring"         , 64 },
    { 0x59, "Crystal Sword"     ,  0 },
    { 0x5a, "Speedboots"        ,  0 },
    { 0x5b, "Flame Horn"        , 60 },
    { 0x5c, "Zen Arrows"        , 10 },
    { 0x5d, "Deathdrum"         , 10 },
    { 0x5e, "Pipes of Pan"      ,  0 },
    { 0x5f, "Power Ring"        , 17 },
    { 0x60, "Song Axe"          ,  0 },
    { 0x61, "Trick Brick"       , 30 },
    { 0x62, "Dragon Fgn"        ,  1 },
    { 0x63, "Mage Fgn"          ,  1 },
    { 0x64, "Troll Ring"        ,  0 },
    { 0x65, "Aram's Knife"      , 30 },
    { 0x66, "Angra's Eye"       ,  7 },
    { 0x67, "Herb Fgn"          ,  1 },
    { 0x68, "Master Wand"       , 11 },
    { 0x69, "Brothers Fgn"      ,  1 },
    { 0x6a, "Dynamite"          ,  1 },
    { 0x6b, "Thor's Hammer"     ,  0 },
    { 0x6c, "Stoneblade"        ,  0 },
    { 0x6d, "Holy Handgrenade"  ,  1 },
    { 0x6e, "Masterkey"         ,  0 },
    { 0x6f, "Nospin Ring"       ,  0 },
    { 0x70, "Crystal Lens"      ,  0 },
    { 0x71, "Smokey Lens"       ,  0 },
    { 0x72, "Black Lens"        ,  0 },
    { 0x73, "Sphere of Lanatir" ,  0 },
    { 0x74, "Wand of Power"     ,  0 },
    { 0x75, "Acorn"             ,  1 },
    { 0x76, "Wineskin"          , 10 },
    { 0x77, "Nightspear"        ,  0 },
    { 0x78, "Tslotha's Head"    ,  0 },
    { 0x79, "Tslotha's Heart"   ,  0 },
    { 0x7a, "Arefolia"          ,  1 },
    { 0x7b, "Valarian's Bow"    ,  0 },
    { 0x7c, "Arws of Life"      , 24 },
    { 0x7d, "Canteen"           , 10 },
    { 0x7e, "Titan Plate"       ,  0 },
    { 0x7f, "Titan Shield"      ,  0 },
    { 0x80, "Titan Helm"        ,  0 },
    { 0x81, "Fire Spear"        ,  1 },
    { 0x82, "Willow Flute"      ,  5 },
    { 0x83, "Firebrand"         ,  0 },
    { 0x84, "Holy Sword"        ,  0 },
    { 0x85, "Wand of Fury"      , 10 },
    { 0x86, "Lightstar"         ,  1 },
    { 0x87, "Crown of Truth"    ,  0 },
    { 0x88, "Belt of Alliria"   ,  0 },
    { 0x89, "Crystal Key"       ,  0 },
    { 0x8a, "Tao Ring"          ,  0 },
    { 0x8b, "Stealth Arrows"    , 24 },
    { 0x8c, "Yellow Staff"      ,  0 },
    { 0x8d, "Steady Eye"        ,  0 },
    { 0x8e, "Divine Halbard"    ,  0 },
    { 0x8f, "Incense"           ,  3 },
    { 0x90, "I-ching"           , 25 },
    { 0x91, "White Rose"        ,  0 },
    { 0x92, "Blue Rose"         ,  0 },
    { 0x93, "Red Rose"          ,  0 },
    { 0x94, "Yellow Rose"       ,  0 },
    { 0x95, "Rainbow Rose"      ,  0 },
    { 0x96, "Magic Triangle"    ,  0 },
    { 0x00, NULL                ,  0 },
    { 0x98, "Hammer of Wrath"   ,  0 },
    { 0x99, "Ferofist's Helm"   ,  0 },
    { 0x00, NULL                ,  0 },
    { 0x00, NULL                ,  0 },
    { 0x9c, "Helm of Justice"   ,  0 },
    { 0x9d, "Sceadu's Cloak"    ,  0 },
    { 0x9e, "Shadelance"        ,  0 },
    { 0x9f, "Black Arrows"      , 24 },
    { 0xa0, "Werra's Shield"    ,  0 },
    { 0xa1, "Strifespear"       ,  0 },
    { 0xa2, "Sheetmusic"        ,  0 },
    { 0xa3, "Right Key"         ,  0 },
    { 0xa4, "Left Key"          ,  0 },
    { 0xa5, "Lever"             ,  0 },
    { 0xa6, "Nut"               ,  0 },
    { 0xa7, "Bolt"              ,  0 },
    { 0xa8, "Spanner"           ,  0 },
    { 0xa9, "Shadow Lock"       ,  0 },
    { 0xaa, "Shadow Door"       ,  0 },
    { 0xab, "Misercorde"        ,  0 },
    { 0xac, "Holy Avenger"      ,  0 },
    { 0xad, "Shadowshiv"        ,  0 },
    { 0xae, "Kali's Garrote"    ,  0 },
    { 0xaf, "Flame Knife"       , 20 },
    { 0xb0, "Red's Stilleto"    ,  0 },
    { 0xb1, "Heartseeker"       ,  0 },
    { 0x00, NULL                ,  0 },
    { 0x00, NULL                ,  0 },
    { 0x00, NULL                ,  0 },
    { 0xb5, "Dmnd Scale"        ,  0 },
    { 0xb6, "Holy TNT"          ,  2 },
    { 0xb7, "Eternal Torch"     ,  0 },
    { 0xb8, "Oscon's Staff"     , 10 },
    { 0xb9, "Angel's Ring"      ,  0 },
    { 0xba, "Deathhorn"         , 30 },
    { 0xbb, "Staff of Mangar"   ,  0 },
    { 0xbc, "Tesla Ring"        , 25 },
    { 0xbd, "Dmnd Bracers"      ,  0 },
    { 0xbe, "Death Fgn"         ,  1 },
    { 0xbf, "Thunder Sword"     ,  0 },
    { 0xc0, "Poison Dagger"     ,  0 },
    { 0xc1, "Spark Blade"       ,  0 },
    { 0xc2, "Galvanic Oboe"     ,  5 },
    { 0xc3, "Harmonic Gem"      ,  1 },
    { 0xc4, "Tung Shield"       ,  0 },
    { 0xc5, "Tung Plate"        ,  0 },
    { 0xc6, "Minstrels Glove"   ,  0 },
    { 0xc7, "Hunters Cloak"     ,  0 },
    { 0xc8, "Death Hammer"      ,  0 },
    { 0xc9, "Blood Mesh Robe"   ,  0 },
    { 0xca, "Soothing Balm"     ,  5 },
    { 0xcb, "Mages Cloak"       , 10 },
    { 0xcc, "Familiar Fgn"      ,  0 },
    { 0xcd, "Hourglass"         ,  2 },
    { 0xce, "Thieves Hood"      ,  0 },
    { 0xcf, "Surehand Amulet"   ,  0 },
    { 0xd0, "Thieves Dart"      ,  1 },
    { 0xd1, "Shrill Flute"      ,  5 },
    { 0xd2, "Angel's Harp"      ,  5 },
    { 0xd3, "The Book"          ,  4 },
    { 0xd4, "Troth Lance"       ,  0 },
    { 0xd5, "Dmnd Suit"         ,  0 },
    { 0xd6, "Dmnd Flail"        ,  0 },
    { 0xd7, "Purple Heart"      , 10 },
    { 0xd8, "Titan Bracers"     ,  0 },
    { 0xd9, "Eelskin Tunic"     ,  0 },
    { 0xda, "Sorcerer's Hood"   ,  0 },
    { 0xdb, "Dmnd Staff"        ,  0 },
    { 0xdc, "Crystal Gem"       ,  3 },
    { 0xdd, "Wand of Force"     , 10 },
    { 0xde, "Cli Lyre"          , 15 },
    { 0xdf, "Youth Potion"      , 10 },
    { 0x00, NULL                ,  0 },
    { 0x00, NULL                ,  0 },
    { 0x00, NULL                ,  0 },
    { 0x00, NULL                ,  0 },
    { 0x00, NULL                ,  0 },
    { 0x00, NULL                ,  0 },
    { 0x00, NULL                ,  0 },
    { 0x00, NULL                ,  0 },
    { 0x00, NULL                ,  0 },
    { 0x00, NULL                ,  0 },
    { 0x00, NULL                ,  0 },
    { 0x00, NULL                ,  0 },
    { 0x00, NULL                ,  0 },
    { 0x00, NULL                ,  0 },
    { 0x00, NULL                ,  0 },
    { 0x00, NULL                ,  0 },
    { 0xf0, "Mthr Suit"         ,  0 },
    { 0xf1, "Titan Suit"        ,  0 },
    { 0xf2, "Mages Gloves"      ,  0 },
    { 0xf3, "Flare Crystal"     ,  5 },
    { 0xf4, "Holy Missile"      ,  1 },
    { 0xf5, "Gods' Blade"       ,  0 },
    { 0xf6, "Hunter Blade"      ,  0 },
    { 0xf7, "Staff of Gods"     , 10 },
    { 0xf8, "Horn of Gods"      , 25 },
    { 0x00, NULL                ,  0 },
    { 0x00, NULL                ,  0 },
    { 0x00, NULL                ,  0 },
    { 0x00, NULL                ,  0 },
    { 0x00, NULL                ,  0 },
    { 0x00, NULL                ,  0 },
    { 0x00, NULL                ,  0 }


/*    {    0, "",                  0 },
    { 0x01, "Torch            ", 1 },
    { 0x02, "Lamp             ", 1 },
    { 0x03, "Broadsword       ", 0 },  
    { 0x04, "Short Sword      ", 0 },  
    { 0x05, "Dagger           ", 0 },  
    { 0x06, "War Axe          ", 1 },
    { 0x07, "Halbard          ", 0 },  
    { 0x08, "Long Bow         ", 0 },  
    { 0x09, "Staff            ", 0 },  
    { 0x0a, "Buckler          ", 0 },  
    { 0x0b, "Tower Shield     ", 0 },  
    { 0x0c, "Leather Armor    ", 0 },  
    { 0x0d, "Chain Mail       ", 0 },  
    { 0x0e, "Scale Armor      ", 0 },  
    { 0x0f, "Plate Armor      ", 0 },  
    { 0x10, "Robes            ", 0 },  
    { 0x11, "Helm             ", 0 },  
    { 0x12, "Leather Gloves   ", 0 },  
    { 0x13, "Gauntlets        ", 0 },  
    { 0x14, "Mandolin         ", 0 },  
    { 0x15, "Spear            ", 1 },
    { 0x16, "Arrows           ", 1 },
    { 0x17, "Mthr Sword       ", 0 },  
    { 0x18, "Mthr Shield      ", 0 },  
    { 0x19, "Mthr Chain       ", 0 },  
    { 0x1a, "Mthr Scale       ", 0 },  
    { 0x1b, "Giant Fgn        ", 1 },
    { 0x1c, "Mthr Bracers     ", 0 },  
    { 0x1d, "Bardsword        ", 0 },  
    { 0x1e, "Fire Horn        ", 1 },
    { 0x1f, "Litewand         ", 1 },
    { 0x20, "Mthr Dagger      ", 0 },  
    { 0x21, "Mthr Helm        ", 0 },  
    { 0x22, "Mthr Gloves      ", 0 },  
    { 0x23, "Mthr Axe         ", 1 },
    { 0x24, "Shuriken         ", 1 },
    { 0x25, "Mthr Plate       ", 0 },  
    { 0x26, "Molten Fgn       ", 1 },
    { 0x27, "Spell Spear      ", 1 },
    { 0x28, "Shield Ring      ", 0 },  
    { 0x29, "Fin's Flute      ", 0 },  
    { 0x2a, "Kael's Axe       ", 1 },
    { 0x2b, "Mthr Arrows      ", 1 },
    { 0x2c, "Dayblade         ", 1 },
    { 0x2d, "Shield Staff     ", 0 },  
    { 0x2e, "Elf Cloak        ", 0 },  
    { 0x2f, "Hawkblade        ", 0 },  
    { 0x30, "Admt Sword       ", 0 },  
    { 0x31, "Admt Shield      ", 0 },  
    { 0x32, "Admt Helm        ", 0 },  
    { 0x33, "Admt Gloves      ", 0 },  
    { 0x34, "Pureblade        ", 0 },  
    { 0x35, "Boomerang        ", 0 },  
    { 0x36, "Ali's Carpet     ", 1 },
    { 0x37, "Luckshield       ", 0 },  
    { 0x38, "Dozer Fgn        ", 1 },
    { 0x39, "Admt Chain       ", 0 },  
    { 0x3a, "Death Stars      ", 1 },
    { 0x3b, "Admt Plate       ", 0 },  
    { 0x3c, "Admt Bracers     ", 0 },  
    { 0x3d, "Slayer Fgn       ", 1 },
    { 0x3e, "Pure Shield      ", 0 },  
    { 0x3f, "Mage Staff       ", 0 },  
    { 0x40, "War Staff        ", 0 },  
    { 0x41, "Thief Dagger     ", 0 },  
    { 0x42, "Soul Mace        ", 0 },  
    { 0x43, "Ogrewand         ", 1 },
    { 0x44, "Kato's bracer    ", 0 },  
    { 0x45, "Sorcerstaff      ", 1 },
    { 0x46, "Galt's Flute     ", 1 },
    { 0x47, "Frost Horn       ", 1 },
    { 0x48, "Ag's Arrows      ", 1 },
    { 0x49, "Dmnd Shield      ", 0 },  
    { 0x4a, "Bard Bow         ", 0 },  
    { 0x4b, "Dmnd Helm        ", 0 },  
    { 0x4c, "Elf Boots        ", 0 },  
    { 0x4d, "Vanquisher Fgn   ", 1 },
    { 0x4e, "Conjurstaff      ", 0 },  
    { 0x4f, "Staff of Lor     ", 1 },
    { 0x50, "Flame Sword      ", 0 },  
    { 0x51, "Powerstaff       ", 1 },
    { 0x52, "Breath Ring      ", 0 },  
    { 0x53, "Dragonshield     ", 1 },
    { 0x54, "Dmnd Plate       ", 0 },  
    { 0x55, "Wargloves        ", 0 },  
    { 0x56, "Wizhelm          ", 1 },
    { 0x57, "Dragonwand       ", 1 },
    { 0x58, "Deathring        ", 1 },
    { 0x59, "Crystal Sword    ", 0 },  
    { 0x5a, "Speedboots       ", 0 },  
    { 0x5b, "Flame Horn       ", 1 },
    { 0x5c, "Zen Arrows       ", 1 },
    { 0x5d, "Deathdrum        ", 1 },
    { 0x5e, "Pipes of Pan     ", 0 },  
    { 0x5f, "Power Ring       ", 1 },
    { 0x60, "Song Axe         ", 0 },  
    { 0x61, "Trick Brick      ", 1 },
    { 0x62, "Dragon Fgn       ", 1 },
    { 0x63, "Mage Fgn         ", 1 },
    { 0x64, "Troll Ring       ", 0 },  
    { 0x65, "Aram's Knife     ", 1 },
    { 0x66, "Angra's Eye      ", 1 },
    { 0x67, "Herb Fgn         ", 1 },
    { 0x68, "Master Wand      ", 1 },
    { 0x69, "Brothers Fgn     ", 1 },
    { 0x6a, "Dynamite         ", 1 },
    { 0x6b, "Thor's Hammer    ", 0 },  
    { 0x6c, "Stoneblade       ", 0 },  
    { 0x6d, "Holy Handgrenade ", 1 },
    { 0x6e, "Masterkey        ", 0 },  
    { 0x6f, "Nospin Ring      ", 0 },  
    { 0x70, "Crystal Lens     ", 0 },  
    { 0x71, "Smokey Lens      ", 0 },  
    { 0x72, "Black Lens       ", 0 },  
    { 0x73, "Sphere of Lanatir", 0 },  
    { 0x74, "Wand of Power    ", 0 },  
    { 0x75, "Acorn            ", 1 },
    { 0x76, "Wineskin         ", 1 },
    { 0x77, "Nightspear       ", 0 },  
    { 0x78, "Tslotha's Head   ", 0 },  
    { 0x79, "Tslotha's Heart  ", 0 },  
    { 0x7a, "Arefolia         ", 1 },
    { 0x7b, "Valarian's Bow   ", 0 },  
    { 0x7c, "Arws of Life     ", 1 },
    { 0x7d, "Canteen          ", 1 },
    { 0x7e, "Titan Plate      ", 0 },  
    { 0x7f, "Titan Shield     ", 0 },  
    { 0x80, "Titan Helm       ", 0 },  
    { 0x81, "Fire Spear       ", 1 },
    { 0x82, "Willow Flute     ", 1 },
    { 0x83, "Firebrand        ", 0 },  
    { 0x84, "Holy Sword       ", 0 },  
    { 0x85, "Wand of Fury     ", 1 },
    { 0x86, "Lightstar        ", 1 },
    { 0x87, "Crown of Truth   ", 0 },  
    { 0x88, "Belt of Alliria  ", 0 },  
    { 0x89, "Crystal Key      ", 0 },  
    { 0x8a, "Tao Ring         ", 0 },  
    { 0x8b, "Stealth Arrows   ", 1 },
    { 0x8c, "Yellow Staff     ", 0 },  
    { 0x8d, "Steady Eye       ", 0 },  
    { 0x8e, "Divine Halbard   ", 0 },  
    { 0x8f, "Incense          ", 1 },
    { 0x90, "I-ching          ", 1 },
    { 0x91, "White Rose       ", 0 },  
    { 0x92, "Blue Rose        ", 0 },  
    { 0x93, "Red Rose         ", 0 },  
    { 0x94, "Yellow Rose      ", 0 },  
    { 0x95, "Rainbow Rose     ", 0 },  
    { 0x96, "Magic Triangle   ", 0 },
    { 0x00, "",                  0 },
    { 0x98, "Hammer of Wrath  ", 0 },  
    { 0x99, "Ferofist's Helm  ", 0 },  
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x9c, "Helm of Justice  ", 0 },  
    { 0x9d, "Sceadu's Cloak   ", 0 },  
    { 0x9e, "Shadelance       ", 0 },  
    { 0x9f, "Black Arrows     ", 1 },
    { 0xa0, "Werra's Shield   ", 0 },  
    { 0xa1, "Strifespear      ", 0 },  
    { 0xa2, "Sheetmusic       ", 0 },  
    { 0xa3, "Right Key        ", 0 },  
    { 0xa4, "Left Key         ", 0 },  
    { 0xa5, "Lever            ", 0 },  
    { 0xa6, "Nut              ", 0 },  
    { 0xa7, "Bolt             ", 0 },  
    { 0xa8, "Spanner          ", 0 },  
    { 0xa9, "Shadow Lock      ", 0 },  
    { 0xaa, "Shadow Door      ", 0 },  
    { 0xab, "Misercorde       ", 0 },  
    { 0xac, "Holy Avenger     ", 0 },  
    { 0xad, "Shadowshiv       ", 0 },  
    { 0xae, "Kali's Garrote   ", 0 },  
    { 0xaf, "Flame Knife      ", 1 },
    { 0xb0, "Red's Stilleto   ", 0 },  
    { 0xb1, "Heartseeker      ", 0 },  
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0xb5, "Dmnd Scale       ", 0 },  
    { 0xb6, "Holy TNT         ", 1 },
    { 0xb7, "Eternal Torch    ", 0 },  
    { 0xb8, "Oscon's Staff    ", 1 },
    { 0xb9, "Angel's Ring     ", 0 },  
    { 0xba, "Deathhorn        ", 1 },
    { 0xbb, "Staff of Mangar  ", 0 },  
    { 0xbc, "Tesla Ring       ", 1 },
    { 0xbd, "Dmnd Bracers     ", 0 },  
    { 0xbe, "Death Fgn        ", 1 },
    { 0xbf, "Thunder Sword    ", 0 },  
    { 0xc0, "Poison Dagger    ", 0 },  
    { 0xc1, "Spark Blade      ", 0 },  
    { 0xc2, "Galvanic Oboe    ", 1 },
    { 0xc3, "Harmonic Gem     ", 1 },
    { 0xc4, "Tung Shield      ", 0 },  
    { 0xc5, "Tung Plate       ", 0 },  
    { 0xc6, "Minstrels Glove  ", 0 },  
    { 0xc7, "Hunters Cloak    ", 0 },  
    { 0xc8, "Death Hammer     ", 0 },  
    { 0xc9, "Blood Mesh Robe  ", 0 },  
    { 0xca, "Soothing Balm    ", 1 },
    { 0xcb, "Mages Cloak      ", 1 },
    { 0xcc, "Familiar Fgn     ", 0 },  
    { 0xcd, "Hourglass        ", 1 },
    { 0xce, "Thieves Hood     ", 0 },  
    { 0xcf, "Surehand Amulet  ", 0 },  
    { 0xd0, "Thieves Dart     ", 1 },
    { 0xd1, "Shrill Flute     ", 1 },
    { 0xd2, "Angel's Harp     ", 1 },
    { 0xd3, "The Book         ", 1 },
    { 0xd4, "Troth Lance      ", 0 },  
    { 0xd5, "Dmnd Suit        ", 0 },  
    { 0xd6, "Dmnd Flail       ", 0 },  
    { 0xd7, "Purple Heart     ", 1 },
    { 0xd8, "Titan Bracers    ", 0 },  
    { 0xd9, "Eelskin Tunic    ", 0 },  
    { 0xda, "Sorcerer's Hood  ", 0 },  
    { 0xdb, "Dmnd Staff       ", 0 },  
    { 0xdc, "Crystal Gem      ", 1 },
    { 0xdd, "Wand of Force    ", 1 },
    { 0xde, "Cli Lyre         ", 1 },
    { 0xdf, "Youth Potion     ", 1 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0xf0, "Mthr Suit        ", 0 },  
    { 0xf1, "Titan Suit       ", 0 },  
    { 0xf2, "Mages Gloves     ", 0 },  
    { 0xf3, "Flare Crystal    ", 1 },
    { 0xf4, "Holy Missile     ", 1 },
    { 0xf5, "Gods' Blade      ", 0 },  
    { 0xf6, "Hunter Blade     ", 0 },  
    { 0xf7, "Staff of Gods    ", 1 },
    { 0xf8, "Horn of Gods     ", 1 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },*/
};

uint8_t items_indexed[226] = {
    0x75,
    0x3c,
    0x39,
    0x33,
    0x32,
    0x3b,
    0x31,
    0x30,
    0x48,
    0x36,
    0xd2,
    0xb9,
    0x66,
    0x65,
    0x7a,
    0x16,
    0x7c,
    0x4a,
    0x1d,
    0x88,
    0x9f,
    0x72,
    0xc9,
    0x92,
    0xa7,
    0x35,
    0x52,
    0x03,
    0x69,
    0x0a,
    0x7d,
    0x0d,
    0xde,
    0x4e,
    0x87,
    0xdc,
    0x89,
    0x70,
    0x59,
    0x05,
    0x2c,
    0xbe,
    0xc8,
    0x3a,
    0x5d,
    0xba,
    0x58,
    0x8e,
    0xbd,
    0xd6,
    0x4b,
    0x54,
    0xb5,
    0x49,
    0xdb,
    0xd5,
    0x38,
    0x62,
    0x53,
    0x57,
    0x6a,
    0xd9,
    0x4c,
    0x2e,
    0xb7,
    0xcc,
    0x99,
    0x29,
    0x1e,
    0x81,
    0x83,
    0x5b,
    0xaf,
    0x50,
    0xf3,
    0x47,
    0x46,
    0xc2,
    0x13,
    0x1b,
    0xf5,
    0x07,
    0x98,
    0xc3,
    0x2f,
    0xb1,
    0x11,
    0x9c,
    0x67,
    0xac,
    0x6d,
    0xf4,
    0x84,
    0xb6,
    0xf8,
    0xcd,
    0xf6,
    0xc7,
    0x90,
    0x8f,
    0x2a,
    0xae,
    0x44,
    0x02,
    0x0c,
    0x12,
    0xa4,
    0xa5,
    0x86,
    0x1f,
    0x08,
    0x37,
    0x63,
    0x3f,
    0xcb,
    0xf2,
    0x96,
    0x14,
    0x68,
    0x6e,
    0xc6,
    0xab,
    0x26,
    0x2b,
    0x23,
    0x1c,
    0x19,
    0x20,
    0x22,
    0x21,
    0x25,
    0x1a,
    0x18,
    0xf0,
    0x17,
    0x77,
    0x6f,
    0xa6,
    0x43,
    0xb8,
    0x5e,
    0x0f,
    0xc0,
    0x5f,
    0x51,
    0x3e,
    0x34,
    0xd7,
    0x95,
    0x93,
    0xb0,
    0xa3,
    0x10,
    0x0e,
    0x9d,
    0x9e,
    0xaa,
    0xa9,
    0xad,
    0xa2,
    0x28,
    0x2d,
    0x04,
    0xd1,
    0x24,
    0x3d,
    0x71,
    0x60,
    0xca,
    0xda,
    0x45,
    0x42,
    0xa8,
    0xc1,
    0x15,
    0x5a,
    0x27,
    0x73,
    0x09,
    0xf7,
    0x4f,
    0xbb,
    0x8d,
    0x8b,
    0x6c,
    0xa1,
    0xcf,
    0x8a,
    0xbc,
    0xd3,
    0x41,
    0xd0,
    0xce,
    0x6b,
    0xbf,
    0xd8,
    0x80,
    0x7e,
    0x7f,
    0xf1,
    0x01,
    0x0b,
    0x61,
    0x64,
    0xd4,
    0x78,
    0x79,
    0xc5,
    0xc4,
    0x7b,
    0x4d,
    0xdd,
    0x85,
    0x74,
    0x06,
    0x40,
    0x55,
    0xa0,
    0x91,
    0x82,
    0x76,
    0x56,
    0x94,
    0x8c,
    0xdf,
    0x5c
};

uint8_t alphabetical_index[26] = {
//   a   b   c   d   e   f   g   h   i   j   k   l   m  
     0, 17, 30, 39, 61, 65, 76, 81, 98,100,100,103,112,
//     n   o   p   q   r   s   t   u   v   w   x   y   z
     135,138,140,148,148,153,187,209,209,211,222,222,225
};

char* get_item_name(uint8_t id)
{
    return item_names[id].text;
}

uint8_t get_item_uses(uint8_t id)
{
    return item_names[id].uses;
}

uint8_t get_itemid_by_index(uint8_t index)
{
    if (index >= get_item_count()) return 0;
    return items_indexed[index];
}

uint8_t get_item_count()
{
    return sizeof(items_indexed);
}

uint8_t get_index_itemid(uint8_t id)
{
    uint8_t i, max;
    max = get_item_count();
    for (i=0; i<sizeof(items_indexed); i++) {
        if (items_indexed[i] == id) return i;
    }
    return 0;
}

uint8_t get_alphabetical_index(uint8_t letter)
{
    letter -= 'a';
    return alphabetical_index[letter];
}
