// Copyright 2023 Drunella
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ----------------------------------------------------------------------------


#include <stdbool.h>
#include <stdio.h>
#include <conio.h>
#include <string.h>
#include <ctype.h>
#include <stdlib.h>

#include "util.h"
#include "editor.h"


text_entry_t item_names[256] = {
    {    0, "",                  0 },
    { 0x01, "Torch            ", 1 },
    { 0x02, "Lamp             ", 1 },
    { 0x03, "Broadsword       ", 0 },  
    { 0x04, "Short Sword      ", 0 },  
    { 0x05, "Dagger           ", 0 },  
    { 0x06, "War Axe          ", 1 },
    { 0x07, "Halbard          ", 0 },  
    { 0x08, "Long Bow         ", 0 },  
    { 0x09, "Staff            ", 0 },  
    { 0x0a, "Buckler          ", 0 },  
    { 0x0b, "Tower Shield     ", 0 },  
    { 0x0c, "Leather Armor    ", 0 },  
    { 0x0d, "Chain Mail       ", 0 },  
    { 0x0e, "Scale Armor      ", 0 },  
    { 0x0f, "Plate Armor      ", 0 },  
    { 0x10, "Robes            ", 0 },  
    { 0x11, "Helm             ", 0 },  
    { 0x12, "Leather Gloves   ", 0 },  
    { 0x13, "Gauntlets        ", 0 },  
    { 0x14, "Mandolin         ", 0 },  
    { 0x15, "Spear            ", 1 },
    { 0x16, "Arrows           ", 1 },
    { 0x17, "Mthr Sword       ", 0 },  
    { 0x18, "Mthr Shield      ", 0 },  
    { 0x19, "Mthr Chain       ", 0 },  
    { 0x1a, "Mthr Scale       ", 0 },  
    { 0x1b, "Giant Fgn        ", 1 },
    { 0x1c, "Mthr Bracers     ", 0 },  
    { 0x1d, "Bardsword        ", 0 },  
    { 0x1e, "Fire Horn        ", 1 },
    { 0x1f, "Litewand         ", 1 },
    { 0x20, "Mthr Dagger      ", 0 },  
    { 0x21, "Mthr Helm        ", 0 },  
    { 0x22, "Mthr Gloves      ", 0 },  
    { 0x23, "Mthr Axe         ", 1 },
    { 0x24, "Shuriken         ", 1 },
    { 0x25, "Mthr Plate       ", 0 },  
    { 0x26, "Molten Fgn       ", 1 },
    { 0x27, "Spell Spear      ", 1 },
    { 0x28, "Shield Ring      ", 0 },  
    { 0x29, "Fin's Flute      ", 0 },  
    { 0x2a, "Kael's Axe       ", 1 },
    { 0x2b, "Mthr Arrows      ", 1 },
    { 0x2c, "Dayblade         ", 1 },
    { 0x2d, "Shield Staff     ", 0 },  
    { 0x2e, "Elf Cloak        ", 0 },  
    { 0x2f, "Hawkblade        ", 0 },  
    { 0x30, "Admt Sword       ", 0 },  
    { 0x31, "Admt Shield      ", 0 },  
    { 0x32, "Admt Helm        ", 0 },  
    { 0x33, "Admt Gloves      ", 0 },  
    { 0x34, "Pureblade        ", 0 },  
    { 0x35, "Boomerang        ", 0 },  
    { 0x36, "Ali's Carpet     ", 1 },
    { 0x37, "Luckshield       ", 0 },  
    { 0x38, "Dozer Fgn        ", 1 },
    { 0x39, "Admt Chain       ", 0 },  
    { 0x3a, "Death Stars      ", 1 },
    { 0x3b, "Admt Plate       ", 0 },  
    { 0x3c, "Admt Bracers     ", 0 },  
    { 0x3d, "Slayer Fgn       ", 1 },
    { 0x3e, "Pure Shield      ", 0 },  
    { 0x3f, "Mage Staff       ", 0 },  
    { 0x40, "War Staff        ", 0 },  
    { 0x41, "Thief Dagger     ", 0 },  
    { 0x42, "Soul Mace        ", 0 },  
    { 0x43, "Ogrewand         ", 1 },
    { 0x44, "Kato's bracer    ", 0 },  
    { 0x45, "Sorcerstaff      ", 1 },
    { 0x46, "Galt's Flute     ", 1 },
    { 0x47, "Frost Horn       ", 1 },
    { 0x48, "Ag's Arrows      ", 1 },
    { 0x49, "Dmnd Shield      ", 0 },  
    { 0x4a, "Bard Bow         ", 0 },  
    { 0x4b, "Dmnd Helm        ", 0 },  
    { 0x4c, "Elf Boots        ", 0 },  
    { 0x4d, "Vanquisher Fgn   ", 1 },
    { 0x4e, "Conjurstaff      ", 0 },  
    { 0x4f, "Staff of Lor     ", 1 },
    { 0x50, "Flame Sword      ", 0 },  
    { 0x51, "Powerstaff       ", 1 },
    { 0x52, "Breath Ring      ", 0 },  
    { 0x53, "Dragonshield     ", 1 },
    { 0x54, "Dmnd Plate       ", 0 },  
    { 0x55, "Wargloves        ", 0 },  
    { 0x56, "Wizhelm          ", 1 },
    { 0x57, "Dragonwand       ", 1 },
    { 0x58, "Deathring        ", 1 },
    { 0x59, "Crystal Sword    ", 0 },  
    { 0x5a, "Speedboots       ", 0 },  
    { 0x5b, "Flame Horn       ", 1 },
    { 0x5c, "Zen Arrows       ", 1 },
    { 0x5d, "Deathdrum        ", 1 },
    { 0x5e, "Pipes of Pan     ", 0 },  
    { 0x5f, "Power Ring       ", 1 },
    { 0x60, "Song Axe         ", 0 },  
    { 0x61, "Trick Brick      ", 1 },
    { 0x62, "Dragon Fgn       ", 1 },
    { 0x63, "Mage Fgn         ", 1 },
    { 0x64, "Troll Ring       ", 0 },  
    { 0x65, "Aram's Knife     ", 1 },
    { 0x66, "Angra's Eye      ", 1 },
    { 0x67, "Herb Fgn         ", 1 },
    { 0x68, "Master Wand      ", 1 },
    { 0x69, "Brothers Fgn     ", 1 },
    { 0x6a, "Dynamite         ", 1 },
    { 0x6b, "Thor's Hammer    ", 0 },  
    { 0x6c, "Stoneblade       ", 0 },  
    { 0x6d, "Holy Handgrenade ", 1 },
    { 0x6e, "Masterkey        ", 0 },  
    { 0x6f, "Nospin Ring      ", 0 },  
    { 0x70, "Crystal Lens     ", 0 },  
    { 0x71, "Smokey Lens      ", 0 },  
    { 0x72, "Black Lens       ", 0 },  
    { 0x73, "Sphere of Lanatir", 0 },  
    { 0x74, "Wand of Power    ", 0 },  
    { 0x75, "Acorn            ", 1 },
    { 0x76, "Wineskin         ", 1 },
    { 0x77, "Nightspear       ", 0 },  
    { 0x78, "Tslotha's Head   ", 0 },  
    { 0x79, "Tslotha's Heart  ", 0 },  
    { 0x7a, "Arefolia         ", 1 },
    { 0x7b, "Valarian's Bow   ", 0 },  
    { 0x7c, "Arws of Life     ", 1 },
    { 0x7d, "Canteen          ", 1 },
    { 0x7e, "Titan Plate      ", 0 },  
    { 0x7f, "Titan Shield     ", 0 },  
    { 0x80, "Titan Helm       ", 0 },  
    { 0x81, "Fire Spear       ", 1 },
    { 0x82, "Willow Flute     ", 1 },
    { 0x83, "Firebrand        ", 0 },  
    { 0x84, "Holy Sword       ", 0 },  
    { 0x85, "Wand of Fury     ", 1 },
    { 0x86, "Lightstar        ", 1 },
    { 0x87, "Crown of Truth   ", 0 },  
    { 0x88, "Belt of Alliria  ", 0 },  
    { 0x89, "Crystal Key      ", 0 },  
    { 0x8a, "Tao Ring         ", 0 },  
    { 0x8b, "Stealth Arrows   ", 1 },
    { 0x8c, "Yellow Staff     ", 0 },  
    { 0x8d, "Steady Eye       ", 0 },  
    { 0x8e, "Divine Halbard   ", 0 },  
    { 0x8f, "Incense          ", 1 },
    { 0x90, "I-ching          ", 1 },
    { 0x91, "White Rose       ", 0 },  
    { 0x92, "Blue Rose        ", 0 },  
    { 0x93, "Red Rose         ", 0 },  
    { 0x94, "Yellow Rose      ", 0 },  
    { 0x95, "Rainbow Rose     ", 0 },  
    { 0x96, "Magic Triangle   ", 0 },
    { 0x00, "",                  0 },
    { 0x98, "Hammer of Wrath  ", 0 },  
    { 0x99, "Ferofist's Helm  ", 0 },  
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x9c, "Helm of Justice  ", 0 },  
    { 0x9d, "Sceadu's Cloak   ", 0 },  
    { 0x9e, "Shadelance       ", 0 },  
    { 0x9f, "Black Arrows     ", 1 },
    { 0xa0, "Werra's Shield   ", 0 },  
    { 0xa1, "Strifespear      ", 0 },  
    { 0xa2, "Sheetmusic       ", 0 },  
    { 0xa3, "Right Key        ", 0 },  
    { 0xa4, "Left Key         ", 0 },  
    { 0xa5, "Lever            ", 0 },  
    { 0xa6, "Nut              ", 0 },  
    { 0xa7, "Bolt             ", 0 },  
    { 0xa8, "Spanner          ", 0 },  
    { 0xa9, "Shadow Lock      ", 0 },  
    { 0xaa, "Shadow Door      ", 0 },  
    { 0xab, "Misercorde       ", 0 },  
    { 0xac, "Holy Avenger     ", 0 },  
    { 0xad, "Shadowshiv       ", 0 },  
    { 0xae, "Kali's Garrote   ", 0 },  
    { 0xaf, "Flame Knife      ", 1 },
    { 0xb0, "Red's Stilleto   ", 0 },  
    { 0xb1, "Heartseeker      ", 0 },  
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0xb5, "Dmnd Scale       ", 0 },  
    { 0xb6, "Holy TNT         ", 1 },
    { 0xb7, "Eternal Torch    ", 0 },  
    { 0xb8, "Oscon's Staff    ", 1 },
    { 0xb9, "Angel's Ring     ", 0 },  
    { 0xba, "Deathhorn        ", 1 },
    { 0xbb, "Staff of Mangar  ", 0 },  
    { 0xbc, "Tesla Ring       ", 1 },
    { 0xbd, "Dmnd Bracers     ", 0 },  
    { 0xbe, "Death Fgn        ", 1 },
    { 0xbf, "Thunder Sword    ", 0 },  
    { 0xc0, "Poison Dagger    ", 0 },  
    { 0xc1, "Spark Blade      ", 0 },  
    { 0xc2, "Galvanic Oboe    ", 1 },
    { 0xc3, "Harmonic Gem     ", 1 },
    { 0xc4, "Tung Shield      ", 0 },  
    { 0xc5, "Tung Plate       ", 0 },  
    { 0xc6, "Minstrels Glove  ", 0 },  
    { 0xc7, "Hunters Cloak    ", 0 },  
    { 0xc8, "Death Hammer     ", 0 },  
    { 0xc9, "Blood Mesh Robe  ", 0 },  
    { 0xca, "Soothing Balm    ", 1 },
    { 0xcb, "Mages Cloak      ", 1 },
    { 0xcc, "Familiar Fgn     ", 0 },  
    { 0xcd, "Hourglass        ", 1 },
    { 0xce, "Thieves Hood     ", 0 },  
    { 0xcf, "Surehand Amulet  ", 0 },  
    { 0xd0, "Thieves Dart     ", 1 },
    { 0xd1, "Shrill Flute     ", 1 },
    { 0xd2, "Angel's Harp     ", 1 },
    { 0xd3, "The Book         ", 1 },
    { 0xd4, "Troth Lance      ", 0 },  
    { 0xd5, "Dmnd Suit        ", 0 },  
    { 0xd6, "Dmnd Flail       ", 0 },  
    { 0xd7, "Purple Heart     ", 1 },
    { 0xd8, "Titan Bracers    ", 0 },  
    { 0xd9, "Eelskin Tunic    ", 0 },  
    { 0xda, "Sorcerer's Hood  ", 0 },  
    { 0xdb, "Dmnd Staff       ", 0 },  
    { 0xdc, "Crystal Gem      ", 1 },
    { 0xdd, "Wand of Force    ", 1 },
    { 0xde, "Cli Lyre         ", 1 },
    { 0xdf, "Youth Potion     ", 1 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0xf0, "Mthr Suit        ", 0 },  
    { 0xf1, "Titan Suit       ", 0 },  
    { 0xf2, "Mages Gloves     ", 0 },  
    { 0xf3, "Flare Crystal    ", 1 },
    { 0xf4, "Holy Missile     ", 1 },
    { 0xf5, "Gods' Blade      ", 0 },  
    { 0xf6, "Hunter Blade     ", 0 },  
    { 0xf7, "Staff of Gods    ", 1 },
    { 0xf8, "Horn of Gods     ", 1 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
    { 0x00, "",                  0 },
};
/*
    { 0x00, ""                },
    { 0x01, "Torch"           },   
    { 0x02, "Lamp"            },   
    { 0x03, "Broadsword"      },   
    { 0x04, "Short Sword"     },   
    { 0x05, "Dagger"          },   
    { 0x06, "War Axe"         },   
    { 0x07, "Halbard"         },   
    { 0x08, "Long Bow"        },   
    { 0x09, "Staff"           },   
    { 0x0a, "Buckler"         },   
    { 0x0b, "Tower Shield"    },   
    { 0x0c, "Leather Armor"   },   
    { 0x0d, "Chain Mail"      },   
    { 0x0e, "Scale Armor"     },   
    { 0x0f, "Plate Armor"     },   
    { 0x10, "Robes"           },   
    { 0x11, "Helm"            },   
    { 0x12, "Leather Gloves"  },   
    { 0x13, "Gauntlets"       },   
    { 0x14, "Mandolin"        },   
    { 0x15, "Spear"           },   
    { 0x16, "Arrows"          },   
    { 0x17, "Mthr Sword"      },   
    { 0x18, "Mthr Shield"     },   
    { 0x19, "Mthr Chain"      },   
    { 0x1a, "Mthr Scale"      },   
    { 0x1b, "Giant Fgn"       },   
    { 0x1c, "Mthr Bracers"    },   
    { 0x1d, "Bardsword"       },   
    { 0x1e, "Fire Horn"       },   
    { 0x1f, "Litewand"        },   
    { 0x20, "Mthr Dagger"     },   
    { 0x21, "Mthr Helm"       },   
    { 0x22, "Mthr Gloves"     },   
    { 0x23, "Mthr Axe"        },   
    { 0x24, "Shuriken"        },   
    { 0x25, "Mthr Plate"      },   
    { 0x26, "Molten Fgn"      },   
    { 0x27, "Spell Spear"     },   
    { 0x28, "Shield Ring"     },   
    { 0x29, "Fin's Flute"     },   
    { 0x2a, "Kael's Axe"      },   
    { 0x2b, "Mthr Arrows"     },   
    { 0x2c, "Dayblade"        },   
    { 0x2d, "Shield Staff"    },   
    { 0x2e, "Elf Cloak"       },   
    { 0x2f, "Hawkblade"       },   
    { 0x30, "Admt Sword"      },   
    { 0x31, "Admt Shield"     },   
    { 0x32, "Admt Helm"       },   
    { 0x33, "Admt Gloves"     },  
    { 0x34, "Pureblade"       },   
    { 0x35, "Boomerang"       },   
    { 0x36, "Ali's Carpet"    },   
    { 0x37, "Luckshield"      },   
    { 0x38, "Dozer Fgn"       },   
    { 0x39, "Admt Chain"      },   
    { 0x3a, "Death Stars"     },   
    { 0x3b, "Admt Plate"      },   
    { 0x3c, "Admt Bracers"    },   
    { 0x3d, "Slayer Fgn"      },   
    { 0x3e, "Pure Shield"     },   
    { 0x3f, "Mage Staff"      },   
    { 0x40, "War Staff"       },   
    { 0x41, "Thief Dagger"    },   
    { 0x42, "Soul Mace"       },   
    { 0x43, "Ogrewand"        },   
    { 0x44, "Kato's bracer"   },   
    { 0x45, "Sorcerstaff"     },   
    { 0x46, "Galt's Flute"    },   
    { 0x47, "Frost Horn"      },   
    { 0x48, "Ag's Arrows"     },   
    { 0x49, "Dmnd Shield"     },   
    { 0x4a, "Bard Bow"        },   
    { 0x4b, "Dmnd Helm"       },   
    { 0x4c, "Elf Boots"       },  
    { 0x4d, "Vanquisher Fgn"  },   
    { 0x4e, "Conjurstaff"     },   
    { 0x4f, "Staff of Lor"    },   
    { 0x50, "Flame Sword"     },   
    { 0x51, "Powerstaff"      },   
    { 0x52, "Breath Ring"     },   
    { 0x53, "Dragonshield"    },   
    { 0x54, "Dmnd Plate"      },   
    { 0x55, "Wargloves"       },   
    { 0x56, "Wizhelm"         },   
    { 0x57, "Dragonwand"      },   
    { 0x58, "Deathring"       },   
    { 0x59, "Crystal Sword"   },   
    { 0x5a, "Speedboots"      },   
    { 0x5b, "Flame Horn"      },   
    { 0x5c, "Zen Arrows"      },
    { 0x5d, "Deathdrum"       },   
    { 0x5e, "Pipes of Pan"    },   
    { 0x5f, "Power Ring"      },   
    { 0x60, "Song Axe"        },   
    { 0x61, "Trick Brick"     },   
    { 0x62, "Dragon Fgn"      },   
    { 0x63, "Mage Fgn"        },   
    { 0x64, "Troll Ring"      },   
    { 0x65, "Aram's Knife"    },   
    { 0x66, "Angra's Eye"     },   
    { 0x67, "Herb Fgn"        },   
    { 0x68, "Master Wand"     },   
    { 0x69, "Brothers Fgn"    },   
    { 0x6a, "Dynamite"        },   
    { 0x6b, "Thor's Hammer"   },   
    { 0x6c, "Stoneblade"      },   
    { 0x6d, "Holy Handgrenade"},
    { 0x6e, "Masterkey"       },
    { 0x6f, "Nospin Ring"     },   
    { 0x70, "Crystal Lens"    },   
    { 0x71, "Smokey Lens"     },   
    { 0x72, "Black Lens"      },   
    { 0x73, "Sphere of Lanatir"},
    { 0x74, "Wand of Power"   },   
    { 0x75, "Acorn"           },   
    { 0x76, "Wineskin"        },   
    { 0x77, "Nightspear"      },   
    { 0x78, "Tslotha's Head"  },   
    { 0x79, "Tslotha's Heart" },   
    { 0x7a, "Arefolia"        },   
    { 0x7b, "Valarian's Bow"  },   
    { 0x7c, "Arws of Life"    },   
    { 0x7d, "Canteen"         },   
    { 0x7e, "Titan Plate"     },   
    { 0x7f, "Titan Shield"    },   
    { 0x80, "Titan Helm"      },   
    { 0x81, "Fire Spear"      },   
    { 0x82, "Willow Flute"    },   
    { 0x83, "Firebrand"       },   
    { 0x84, "Holy Sword"      },   
    { 0x85, "Wand of Fury"    },   
    { 0x86, "Lightstar"       },   
    { 0x87, "Crown of Truth"  },   
    { 0x88, "Belt of Alliria" },   
    { 0x89, "Crystal Key"     },   
    { 0x8a, "Tao Ring"        },   
    { 0x8b, "Stealth Arrows"  },   
    { 0x8c, "Yellow Staff"    },   
    { 0x8d, "Steady Eye"      },   
    { 0x8e, "Divine Halbard"  },   
    { 0x8f, "Incense"         },   
    { 0x90, "I-ching"         },   
    { 0x91, "White Rose"      },   
    { 0x92, "Blue Rose"       },   
    { 0x93, "Red Rose"        },   
    { 0x94, "Yellow Rose"     },   
    { 0x95, "Rainbow Rose"    },   
    { 0x96, "Magic Triangle"  },   
    { 0x98, "Hammer of Wrath" },   
    { 0x99, "Ferofist's Helm" },   
    { 0x9c, "Helm of Justice" },   
    { 0x9d, "Sceadu's Cloak"  },   
    { 0x9e, "Shadelance"      },   
    { 0x9f, "Black Arrows"    },   
    { 0xa0, "Werra's Shield"  },   
    { 0xa1, "Strifespear"     },   
    { 0xa2, "Sheetmusic"      },   
    { 0xa3, "Right Key"       },  
    { 0xa4, "Left Key"        },   
    { 0xa5, "Lever"           },   
    { 0xa6, "Nut"             },   
    { 0xa7, "Bolt"            },   
    { 0xa8, "Spanner"         },   
    { 0xa9, "Shadow Lock"     },   
    { 0xaa, "Shadow Door"     },   
    { 0xab, "Misercorde"      },   
    { 0xac, "Holy Avenger"    },   
    { 0xad, "Shadowshiv"      },   
    { 0xae, "Kali's Garrote"  },   
    { 0xaf, "Flame Knife"     },   
    { 0xb0, "Red's Stilleto"  },   
    { 0xb1, "Heartseeker"     },   
    { 0xb5, "Dmnd Scale"      },   
    { 0xb6, "Holy TNT"        },   
    { 0xb7, "Eternal Torch"   },   
    { 0xb8, "Oscon's Staff"   },   
    { 0xb9, "Angel's Ring"    },   
    { 0xba, "Deathhorn"       },   
    { 0xbb, "Staff of Mangar" },   
    { 0xbc, "Tesla Ring"      },   
    { 0xbd, "Dmnd Bracers"    },   
    { 0xbe, "Death Fgn"       },   
    { 0xbf, "Thunder Sword"   },   
    { 0xc0, "Poison Dagger"   },   
    { 0xc1, "Spark Blade"     },   
    { 0xc2, "Galvanic Oboe"   },   
    { 0xc3, "Harmonic Gem"    },   
    { 0xc4, "Tung Shield"     },   
    { 0xc5, "Tung Plate"      },   
    { 0xc6, "Minstrels Glove" },   
    { 0xc7, "Hunters Cloak"   },   
    { 0xc8, "Death Hammer"    },   
    { 0xc9, "Blood Mesh Robe" },   
    { 0xca, "Soothing Balm"   },   
    { 0xcb, "Mages Cloak"     },   
    { 0xcc, "Familiar Fgn"    },   
    { 0xcd, "Hourglass"       },   
    { 0xce, "Thieves Hood"    },   
    { 0xcf, "Surehand Amulet" },   
    { 0xd0, "Thieves Dart"    },   
    { 0xd1, "Shrill Flute"    },   
    { 0xd2, "Angel's Harp"    },   
    { 0xd3, "The Book"        },   
    { 0xd4, "Troth Lance"     },   
    { 0xd5, "Dmnd Suit"       },   
    { 0xd6, "Dmnd Flail"      },   
    { 0xd7, "Purple Heart"    },   
    { 0xd8, "Titan Bracers"   },   
    { 0xd9, "Eelskin Tunic"   },   
    { 0xda, "Sorcerer's Hood" },   
    { 0xdb, "Dmnd Staff"      },   
    { 0xdc, "Crystal Gem"     },   
    { 0xdd, "Wand of Force"   },   
    { 0xde, "Cli Lyre"        },   
    { 0xdf, "Youth Potion"    },
    { 0xf0, "Mthr Suit"       },   
    { 0xf1, "Titan Suit"      },   
    { 0xf2, "Mages Gloves"    },   
    { 0xf3, "Flare Crystal"   },   
    { 0xf4, "Holy Missile"    },   
    { 0xf5, "Gods' Blade"     },   
    { 0xf6, "Hunter Blade"    },   
    { 0xf7, "Staff of Gods"   },   
    { 0xf8, "Horn of Gods"    }
};
*/

char* get_item_name(uint8_t id)
{
    return item_names[id].text;
}

uint8_t get_item_flags(uint8_t id)
{
    return item_names[id].flags;
}
